// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootstrapPayload() {
  return window['go']['main']['App']['GetBootstrapPayload']();
}

export function LaunchOpenClaw() {
  return window['go']['main']['App']['LaunchOpenClaw']();
}

export function OpenExternalTarget(arg1) {
  return window['go']['main']['App']['OpenExternalTarget'](arg1);
}

export function RunNativeInstaller(arg1) {
  return window['go']['main']['App']['RunNativeInstaller'](arg1);
}
