// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBootstrapPayload():Promise<main.BootstrapPayload>;

export function LaunchOpenClaw():Promise<void>;

export function RunNativeInstaller(arg1:main.InstallerConfig):Promise<main.InstallerResult>;

export function RunPostInstallActions():Promise<main.PostInstallActionResult>;
